VIEWS : Guardian Request Navigation
Mums-Who-Code/SCMS.Portal pull request #86
Opened 2022-02-18 02:52 UTC by imjane5

2022-02-18 06:01 UTC, ShriHumrudha requested changes

2022-02-18 06:01 UTC, ShriHumrudha commented on SCMS.Portal.Web/Models/Views/Foundations/GuardianRequestViews/Exceptions/InvalidGuardianRequestViewException.cs
> +           : base($"Invalid student view error occured. " +
guardian request

2022-02-18 06:01 UTC, ShriHumrudha commented on SCMS.Portal.Web/Services/Views/Foundations/GuardianRequestViews/GuardianRequestViewService.Validations.cs
> +            string.IsNullOrWhiteSpace(route);
Single line space is required after the method

2022-02-18 06:55 UTC, tharanisantosh commented on SCMS.Portal.Tests.Unit/Services/Views/Foundations/GuardianRequestViews/GuardianRequestViewServiceTests.Validations.Navigate.cs
> +        public void ShouldThrowValidationExceptionOnNavigateIfRouteIsInvalidAndLogitAsync(
Comment Resolved

2022-02-18 06:59 UTC, tharanisantosh commented on SCMS.Portal.Tests.Unit/Services/Views/Foundations/GuardianRequestViews/GuardianRequestViewServiceTests.Validations.Navigate.cs
> +            this.navigationBrokerMock.VerifyNoOtherCalls();
Comment Resolved

2022-02-18 07:02 UTC, tharanisantosh commented on SCMS.Portal.Web/Models/Views/Foundations/GuardianRequestViews/Exceptions/InvalidGuardianRequestViewException.cs
> +           : base($"Invalid student view error occured. " +
Comment Resolved

2022-02-19 04:14 UTC, ShriHumrudha requested changes

2022-02-19 04:14 UTC, ShriHumrudha commented on SCMS.Portal.Tests.Unit/Services/Views/Foundations/GuardianRequestViews/GuardianRequestViewServiceTests.Validations.Navigate.cs
> +               new InvalidGuardianRequestViewException(
Check the alignment here.

2022-02-20 21:41 UTC, ShriHumrudha requested changes

2022-02-20 21:41 UTC, ShriHumrudha commented on SCMS.Portal.Tests.Unit/Services/Views/Foundations/GuardianRequestViews/GuardianRequestViewServiceTests.Validations.Navigate.cs
> +               new InvalidGuardianRequestViewException(
@imjane5 @tharanisantosh - This is pending.

2022-02-22 03:06 UTC, tharanisantosh commented on SCMS.Portal.Tests.Unit/Services/Views/Foundations/GuardianRequestViews/GuardianRequestViewServiceTests.Validations.Navigate.cs
> +               new InvalidGuardianRequestViewException(
Comment Resolved.

2022-02-22 03:14 UTC, ShriHumrudha approved these changes

2022-02-22 03:14 UTC, merged